# -*- coding: utf-8 -*-
"""concat4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O99D2H4eyNe4njaAx2OYQuZjZu-rnV8X
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

df = pd.read_csv('OnlineKhatt.tsv', sep='\t')
 
# printing data
df

# data = []
# for i,j in enumerate(df['text']):
#     data.append(j)

# df = pd.DataFrame(data, columns=['concat5'])
# df

# print (df.groupby(df.index // 5)['text'].agg('\n'.join))

# df['text'].groupby(np.repeat(np.arange(len(df)), 5)[:len(df)]).agg('\n'.join)

df2 = pd.DataFrame({'col':['one','fish','two','fish','left','foot','right','foot']})
df2

output_left = df.groupby(df.index // 5).agg(' '.join)

df = df.dropna()

len(df)

output_right = df.groupby(df.index // 5)['text'].agg('\n'.join)

output = pd.concat([output_left, output_right], axis=1)

# print(df3.groupby(df3.index // 5)['text'].agg(' '.join).to_frame())

output.to_csv('concat_khatt.tsv', sep="\t")

output['file_name'] = 'batch'+(output['file_name'].index + 1).astype(str)+'.jpg'

output

# train_test_split(output, test_size=0.20, random_state=42)

train, test = train_test_split(output, test_size=0.20, random_state=42)

test, val = train_test_split(test, test_size=0.50, random_state=42)

train.to_csv('train.tsv',sep="\t")
test.to_csv('test.tsv',sep="\t")
val.to_csv('val.tsv',sep="\t")

