# -*- coding: utf-8 -*-
"""transforms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VLmRTLCD5J5v3Q1KhDZzWyXBLFQrhEe4
"""

import torch
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda

ds = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
    target_transform=Lambda(lambda y: torch.zeros(10, dtype=torch.float).scatter_(0, torch.tensor(y), value=1))
)

target_transform = Lambda(lambda y: torch.zeros(
    10, dtype=torch.float).scatter_(dim=0, index=torch.tensor(y), value=1))

target_transform

