# -*- coding: utf-8 -*-
"""tortoise_tts_colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1siXlOqFb0X-XYVwXsZ_r9jW34d-DYLjo
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!git clone -b dev https://github.com/camenduru/tortoise-hf
# %cd /content/tortoise-hf
!git clone -b v1.0 https://github.com/camenduru/tortoise-tts

!pip install gradio scipy -U
# %cd /content/tortoise-hf/tortoise-tts
!pip install transformers==4.19.0
!pip install -r requirements.txt
!python setup.py install

# %cd /content/tortoise-hf
!python app.py

